# SPDX-License-Identifier: MIT
if(NOT DEFINED PROJECT_SOURCE_DIR OR PROJECT_SOURCE_DIR STREQUAL "")
    message(FATAL_ERROR "PROJECT_SOURCE_DIR is required")
endif()

foreach(_file CMakeLists.txt library.json library.properties CHANGELOG.md docs/internal/release-notes.md)
    if(NOT EXISTS "${PROJECT_SOURCE_DIR}/${_file}")
        message(FATAL_ERROR "Missing metadata file: ${_file}")
    endif()
endforeach()

file(READ "${PROJECT_SOURCE_DIR}/CMakeLists.txt" _cmake_lists)
file(READ "${PROJECT_SOURCE_DIR}/library.json" _library_json)
file(READ "${PROJECT_SOURCE_DIR}/library.properties" _library_properties)
file(READ "${PROJECT_SOURCE_DIR}/CHANGELOG.md" _changelog)
file(READ "${PROJECT_SOURCE_DIR}/docs/internal/release-notes.md" _release_notes)

string(REGEX MATCH "project\\(loxdb VERSION ([0-9]+\\.[0-9]+\\.[0-9]+)" _cmake_match "${_cmake_lists}")
if(NOT CMAKE_MATCH_1)
    message(FATAL_ERROR "Could not parse project version from CMakeLists.txt")
endif()
set(_cmake_version "${CMAKE_MATCH_1}")

string(REGEX MATCH "\"version\"[ \t]*:[ \t]*\"([^\"]+)\"" _json_match "${_library_json}")
if(NOT CMAKE_MATCH_1)
    message(FATAL_ERROR "Could not parse version from library.json")
endif()
set(_json_version "${CMAKE_MATCH_1}")

string(REGEX MATCH "version=([0-9]+\\.[0-9]+\\.[0-9]+)" _props_match "${_library_properties}")
if(NOT CMAKE_MATCH_1)
    message(FATAL_ERROR "Could not parse version from library.properties")
endif()
set(_props_version "${CMAKE_MATCH_1}")

string(REGEX MATCH "## \\[([0-9]+\\.[0-9]+\\.[0-9]+)\\] -" _changelog_match "${_changelog}")
if(NOT CMAKE_MATCH_1)
    message(FATAL_ERROR "Could not parse released version from CHANGELOG.md")
endif()
set(_changelog_version "${CMAKE_MATCH_1}")

string(REGEX MATCH "loxdb v([0-9]+\\.[0-9]+\\.[0-9]+)" _release_notes_match "${_release_notes}")
if(NOT CMAKE_MATCH_1)
    message(FATAL_ERROR "Could not parse release notes version")
endif()
set(_release_notes_version "${CMAKE_MATCH_1}")

if(NOT _cmake_version STREQUAL _json_version)
    message(FATAL_ERROR "CMakeLists.txt version (${_cmake_version}) does not match library.json (${_json_version})")
endif()
if(NOT _cmake_version STREQUAL _props_version)
    message(FATAL_ERROR "CMakeLists.txt version (${_cmake_version}) does not match library.properties (${_props_version})")
endif()
if(NOT _cmake_version STREQUAL _changelog_version)
    message(FATAL_ERROR "CMakeLists.txt version (${_cmake_version}) does not match CHANGELOG.md (${_changelog_version})")
endif()
if(NOT _cmake_version STREQUAL _release_notes_version)
    message(FATAL_ERROR "CMakeLists.txt version (${_cmake_version}) does not match release notes (${_release_notes_version})")
endif()
